[profile.default]
### solc_version = "0.8.29"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
solc_version = "C:/Python313/solc.exe"
auto_detect_solc = false
offline = true
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@metamask/delegation-framework/=lib/delegation-framework/",
    "@FCL/=lib/delegation-framework/lib/FCL/solidity/src/",
    "@SCL/=lib/delegation-framework/lib/SCL/src/",
    "@account-abstraction/=lib/delegation-framework/lib/account-abstraction/contracts/",
    "@bytes-utils/=lib/delegation-framework/lib/solidity-bytes-utils/contracts/",
    "@erc7579/=lib/delegation-framework/lib/erc7579-implementation/src/",
    "@openzeppelin/contracts-upgradeable/=lib/delegation-framework/lib/openzeppelin-upgradable-contracts/contracts/",
    "@openzeppelin/contracts/=lib/delegation-framework/lib/openzeppelin-contracts/contracts/",
    "@solidity-stringutils/=lib/delegation-framework/lib/solidity-stringutils/src/",
    "@solidity/=lib/delegation-framework/lib/SCL/src/",
    "FCL/=lib/delegation-framework/lib/FCL/solidity/src/",
    "SCL/=lib/delegation-framework/lib/SCL/",
    "account-abstraction/=lib/delegation-framework/lib/account-abstraction/contracts/",
    "delegation-framework/=lib/delegation-framework/",
    "ds-test/=lib/delegation-framework/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/delegation-framework/lib/openzeppelin-contracts/lib/erc4626-tests/",
    "erc7579-implementation/=lib/delegation-framework/lib/erc7579-implementation/src/",
    "forge-std/=lib/delegation-framework/lib/forge-std/src/",
    "openzeppelin-contracts/=lib/delegation-framework/lib/openzeppelin-contracts/",
    "sentinellist/=lib/delegation-framework/lib/erc7579-implementation/node_modules/@rhinestone/sentinellist/src/",
    "solady/=lib/delegation-framework/lib/erc7579-implementation/node_modules/solady/src/",
    "solidity-bytes-utils/=lib/delegation-framework/lib/solidity-bytes-utils/contracts/",
    "solidity-stringutils/=lib/delegation-framework/lib/solidity-stringutils/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

